### ISSUE TITLE
Tracking bug: ZeroMQ

### ISSUE THREAD

**Issue by EdSchouten** [NuxiNL/cloudabi-ports#31]
Hi @laanwj,

As I mentioned previously, I've been working towards getting ZeroMQ to work on CloudABI. I wanted to use this issue to keep track of progress. Anyway, the latest build of CloudABI Ports now includes a ZeroMQ package. To summarise:

- `zmq_connect()` has been disabled. There is no way to connect to queues.
- `zmq_bind()` is a bit weird: you have to use it both when letting the library create the socket, but also when passing one in. This means that we don't have a way of automatically detecting code that needs to be patched up to bind.

Anyway, I still need to test ZeroMQ a bit more extensively. At least this piece of code already builds and runs properly:

```c++
#include <program.h>
#include <stdio.h>
#include <zmq.h>

#include <argdata.hpp>
#include <cassert>
#include <cstdlib>
#include <string_view>

void program_main(const argdata_t *ad) {
  int s = -1;
  for (auto [key, value] : ad->as_map()) {
    std::string_view keystr = key->as_str();
    if (keystr == "terminal") {
      FILE *fp = fdopen(value->as_fd(), "w");
      if (fp != nullptr) {
        setvbuf(fp, nullptr, _IONBF, 0);
        fswap(fp, stderr);
        fclose(fp);
      }
    } else if (keystr == "socket") {
      s = value->as_fd();
    }
  }

  void *context = zmq_ctx_new();
  assert(context != nullptr);
  void *socket = zmq_socket(context, ZMQ_PUB);
  assert(socket != nullptr);
  int rc = zmq_setsockopt(socket, ZMQ_USE_FD, &s, sizeof(s));
  assert(rc == 0);
  rc = zmq_bind(socket, "ipc:///");
  assert(rc == 0);

  std::exit(0);
}
```

It can be used in combination with this config:

```yaml
%TAG ! tag:nuxi.nl,2015:cloudabi/
---
terminal: !fd stdout
socket: !socket
  bind: /tmp/foo
```

**Comment by laanwj** [comment]
I can confirm that this is working with Bitcoin Core. Set it up to broadcast notifications:
```
zmq: !socket
  bind: 0.0.0.0:28332
...
args:
...
  zmqpubhashblock: "ipc:///"
  zmqpubhashtx: "ipc:///"
  zmqpubrawblock: "ipc:///"
  zmqpubrawtx: "ipc:///"
```
Bound the fd to a local port instead of a UNIX socket, but that seems to work too.
Could receive the notifications from a non-CloudABI process.
